#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Passwords aren't saved by default
ynh_app_setting_set --app="$app" --key=userpass --value="$userpass"

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="mosquitto.conf" --destination="/etc/mosquitto/conf.d/default.conf"

touch /etc/mosquitto/passwd
mosquitto_passwd -b "/etc/mosquitto/passwd" "$username" "$userpass"

# Hard coded username because deb package creates the user
chown -R "mosquitto" "/etc/mosquitto"
chmod 600 "/etc/mosquitto/passwd"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

yunohost service add "$app" --description="Allows MQTT clients to send/receive data" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name="$app" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
