#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status "$app" >/dev/null
then
	yunohost service remove "$app"
fi

# Remove the dedicated systemd config
# It seems the simple stop is not enough…
ynh_systemctl --service="$app" --action="stop"
pkill -u "$app" || true
ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_safe_rm "/etc/mosquitto/passwd"

ynh_safe_rm "/etc/mosquitto/conf.d/default.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
