#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="Allows MQTT clients to send/receive data" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/etc/mosquitto/conf.d/default.conf"
ynh_restore "/etc/mosquitto/passwd"
chown -R "mosquitto" "/etc/mosquitto"
chmod 600 "/etc/mosquitto/passwd"

ynh_restore "/var/log/$app/"
chown -R "mosquitto" "/var/log/$app/"

if [ "$(ynh_app_setting_get --key=protocol)" = "secure_mqtt" ]
then
	# Make sure Mosquitto can read the certificates
	usermod -a -G ssl-cert $app
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
