#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/logrotate.d/$app"

yunohost service add "$app" --description="Allows MQTT clients to send/receive data" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"

#=================================================
# RESTORE VARIOUS FILES
#=================================================
ynh_script_progression "Restoring various files..."

ynh_restore "/etc/mosquitto/conf.d/default.conf"
ynh_restore "/etc/mosquitto/passwd"

ynh_restore "/var/log/$app/"

# Hard coded username because deb package creates the user
chown -R "mosquitto" "/etc/mosquitto"

# Make sure Mosquitto can read the certificates
usermod -a -G ssl-cert $app

ynh_config_add --template="index.html" --destination="$install_dir/index.html"
chown -R "$app:www-data" "$install_dir"
chmod 640 "$install_dir/index.html"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
