#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# Transfer and delete the old "password" key
if [ -z "${userpass:-}" ]; then
    userpass="$password"
    ynh_app_setting_set --key="userpass" --value="$userpass"
    ynh_app_setting_delete --key="password"
fi

if [ -z "${domain:-}" ]; then
    ynh_die "This new version requires now a domain. Please read pre_upgrade notes again."
fi

if ynh_app_upgrading_from_version_before 2.0.20~ynh2
then
    ynh_delete_file_checksum "/etc/mosquitto/passwd"
fi

if [ -z ${protocol:-} ]
then
    ynh_app_setting_set --key=protocol --value="secure_mqtt"
fi

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

protocol=$(ynh_app_setting_get --key=protocol)

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

if [ "$protocol" = "secure_mqtt" ]
then
    # Add corresponding configuration file
    ynh_config_add --template="mosquitto_secure.conf" --destination="/etc/mosquitto/conf.d/default.conf"

    # Make sure Mosquitto can read the certificates
    usermod -a -G ssl-cert $app

    # Expose the SSL and websockets ports
    ynh_hide_warnings yunohost firewall allow TCP $port_ssl --no-upnp
    ynh_hide_warnings yunohost firewall allow TCP $port_websockets --no-upnp

else
    # Add corresponding configuration file
    ynh_config_add --template="mosquitto_plain.conf" --destination="/etc/mosquitto/conf.d/default.conf"
fi

# Generate passwd file
touch /etc/mosquitto/passwd
ynh_hide_warnings mosquitto_passwd -b "/etc/mosquitto/passwd" "$username" "$userpass"

# Hard coded username because deb package creates the user
chown -R "mosquitto" "/etc/mosquitto"
chmod 600 "/etc/mosquitto/passwd"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
#ynh_config_add_nginx

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate

yunohost service add "$app" --description="Allows MQTT clients to send/receive data" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
